services:
  apache_ehm:
    image: php:8.1-apache
    container_name: apache_server_ehm
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./php:/var/www/html/php
      - ./css:/var/www/html/css
    ports:
      - "8080:80"
    depends_on:
      - mysql_ehm
    command: >
      bash -c "docker-php-ext-install mysqli && docker-php-ext-enable mysqli && apache2-foreground"

  mysql_ehm:
    image: mysql:latest
    container_name: mysql_ehm
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin_ehm:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ehm
    restart: always
    depends_on:
      - mysql_ehm
    environment:
      PMA_HOST: mysql_ehm
      PMA_USER: root
      PMA_PASSWORD: ""
    ports:
      - "8081:80"

volumes:
  mysql_data:
